##! /bin/bash

######## sep_all.sh (XXX.sh)

######## This file was generated by `tex all.tex' 6.6.2021

echo "Entering sep_all.sh"

pdfseparate all_sep.pdf all_sep-%02d.pdf

echo "Creating toc_ls.pdf with pdfunite"

pdfunite \
all_sep-01.pdf \
all_sep-02.pdf \
all_sep-03.pdf \
all_sep-04.pdf \
all_sep-05.pdf toc_ls.pdf

echo "Creating toc_ls_a_h.pdf with pdfunite"

pdfunite \
all_sep-06.pdf \
all_sep-07.pdf \
all_sep-08.pdf toc_ls_a_h.pdf

echo "Creating toc_ls_i_o.pdf with pdfunite"

pdfunite \
all_sep-09.pdf \
all_sep-10.pdf \
all_sep-11.pdf toc_ls_i_o.pdf

echo "Creating toc_ls_p_z.pdf with pdfunite"

pdfunite \
all_sep-12.pdf \
all_sep-13.pdf \
all_sep-14.pdf toc_ls_p_z.pdf

echo "Creating toc_npt.pdf with pdfunite"

pdfunite \
all_sep-15.pdf \
all_sep-16.pdf toc_npt.pdf

echo "Creating composers.pdf with pdfunite"

pdfunite \
all_sep-17.pdf \
all_sep-18.pdf \
all_sep-19.pdf \
all_sep-20.pdf \
all_sep-21.pdf \
all_sep-22.pdf \
all_sep-23.pdf \
all_sep-24.pdf \
all_sep-25.pdf \
all_sep-26.pdf composers.pdf

echo "Creating lyricists.pdf with pdfunite"

pdfunite \
all_sep-27.pdf \
all_sep-28.pdf \
all_sep-29.pdf \
all_sep-30.pdf \
all_sep-31.pdf \
all_sep-32.pdf \
all_sep-33.pdf \
all_sep-34.pdf \
all_sep-35.pdf lyricists.pdf

echo "Creating scanned.pdf with pdfunite"

pdfunite \
all_sep-36.pdf \
all_sep-37.pdf \
all_sep-38.pdf scanned.pdf

echo "Creating pblcdomn.pdf with pdfunite"

pdfunite \
all_sep-39.pdf \
all_sep-40.pdf pblcdomn.pdf

rm -v -f `find . -regex "./all_sep-[0-9]+.*.pdf"`

echo "Exiting sep_all.sh with exit status 0"
exit 0
